apiVersion: v1
kind: Service
metadata:
  labels:
    service: apollo
  name: apollo
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  selector:
    service: apollo
status:
  loadBalancer: {}
