apiVersion: v1
kind: Service
metadata:
  labels:
    service: graphql
  name: graphql
spec:
  ports:
  - name: "4201"
    port: 4201
    targetPort: 4201
  selector:
    service: graphql
status:
  loadBalancer: {}
